MONGODB_HOST: mongodb-{{ env }}.msdevsecops.fun
REDIS_HOST: redis-{{ env }}.msdevsecops.fun
CATALOGUE_HOST: catalogue-{{ env }}.msdevsecops.fun
MYSQL_HOST: mysql-{{ env }}.msdevsecops.fun
CART_HOST: cart-{{ env }}.msdevsecops.fun
USER_HOST: user-{{ env }}.msdevsecops.fun
RABBITMQ_HOST: rabbitmq-{{ env }}.msdevsecops.fun
SHIPPING_HOST: shipping-{{ env }}.msdevsecops.fun
PAYMENT_HOST: payment-{{ env }}.msdevsecops.fun