MONGODB_HOST: mongodb-{{ env }}.msdevsecops.fun
REDIS_HOST: redis-{{ env }}.msdevsecops.fun
CATALOGUE_HOST: catalogue.backend-alb-{{ env }}.msdevsecops.fun
MYSQL_HOST: mysql-{{ env }}.msdevsecops.fun
CART_HOST: cart.backend-alb-{{ env }}.msdevsecops.fun
USER_HOST: user.backend-alb-{{ env }}.msdevsecops.fun
RABBITMQ_HOST: rabbitmq-{{ env }}.msdevsecops.fun
SHIPPING_HOST: shipping.backend-alb-{{ env }}.msdevsecops.fun
PAYMENT_HOST: payment.backend-alb-{{ env }}.msdevsecops.fun
